### PR TITLE
Add support for duration (elapsed time)

### PR DESCRIPTION
**Pull request by etairi**

### CODE REVIEW

**Comment by headzoo** [comment]
The code looks good. Can you also update the README to include example usage?

**Comment by etairi** [comment]
I just updated the README as how I expect it to be used. I guess the most useful feature is to use `durationFromNow` in combination with `interval` of 1 second, so you can see the continuously updated elapsed time from some provided datetime value. Please note that I haven't tested it fully. I would be glad if you can test it, especially the scenario that I explained above, as it is the most common usage for something like this.

**Comment by headzoo** [comment]
Alright, I'll update the tests and then publish the changes to npm. Thanks!

**Comment by headzoo** [comment]
Published as 0.8.3

**Comment by etairi** [comment]
Thanks, seems to work fine!

**Pull request merged**
