### PR TITLE
Make react-moment work with React 15.5+

### PR DESCRIPTION
**Pull request by sergiocruz**
Hi there 👋 

First things first, thanks for all the work put into this awesome library!

In one of the projects I use it in, we just updated React to 15.5, which brought in some [deprecation warnings](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#new-deprecation-warnings).

I figured I'd take it upon myself to try and help out with making this library work free of warning messages.

Also, I wasn't sure how you handled releases, so I left the version number untouched for the time being.

I hope you find this helpful/useful 😄

### CODE REVIEW

**Comment by A-Dubz** [comment]
Hi @headzoo!

Just curious if you had a timeline for merging PR #18? Thanks!

**Comment by a-x-** [comment]
@headzoo ping!

**Comment by a-x-** [comment]
you should make build and update dist dir

**Comment by a-x-** [comment]
I did it yourself #22

**Comment by sergiocruz** [comment]
@a-x- I presume we need to bump up the version as well. I think this is just a patch, but was hoping that @headzoo would confirm before I amended the PR.

**Comment by kytwb** [comment]
@headzoo ping?

**Comment by chuanxie** [comment]
any update?

**Comment by headzoo** [comment]
Thanks for the PR. I've merged the changes and I'm publishing them to npm now. :)

**Pull request merged**
